# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5cc5b3848641c82486916f157d38f8dbe6054765d1d95a5f5733a5bbf010da7b4078d49f8bc52f8723e40b3d55fdad8be31fc1172367c5c9f070d07db2198a6

test:
  secret_key_base: 8dcf3a60ade730ebdbd3919d1a5f1387721743dbc34a4b17888e711187dd5cfa779c00a13baf39e6f38396e121c8509f913406c27e822949b4bb4dcedd96cbb8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
